#Project Information
site_name: Zensical Docs 
site_url: https://github.com/vishwanathan-m1/material_to_zensical
docs_dir: source
# site_dir: docs
use_directory_urls: false

# Theme Configuration
theme:
  name: material  
  custom_dir: theme_overrides
  palette: 

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: octicons/sun-16
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: octicons/moon-16
        name: Switch to light mode

# Repository
repo_url: https://github.com/vishwanathan-m1/material_to_zensical
repo_name: vishwanathan-m1/material_to_zensical
edit_uri: ""

# Markdown Extensions
markdown_extensions:
  - toc:
      title: On this page

# Copyright
copyright: >-
  Copyright &copy; 2026, HCL Technologies Limited


# Extras
extra:
  homepage: https://help.hcl-software.com/verse_onprem/
  social:
    - icon: fontawesome/brands/github
      link: https://git.cwp.pnp-hcl.com/CWPdoc
  version:
    provider: mike

# Plugins
plugins:
  - search
  - mike:
      canonical_version: latest
      alias_type: redirect

# Navigation
nav:
- Welcome to Zensical: index.md
- About Zensical: about.md
- Module_1:
  - Component_1:
      - Topic_1: Module_1/Component_1/Content/Topic1.md
      - Topic_2: Module_1/Component_1/Content/Topic2.md        
      - Topic_3: Module_1/Component_1/Content/Topic3.md
  - Component_2:
      - Topic_1: Module_1/Component_2/Content/Topic1.md
      - Topic_2: Module_1/Component_2/Content/Topic2.md
- Module_2:
  - Component_3:
      - Topic_1: Module_2/Component_3/Content/Topic1.md
      - Topic_2: Module_2/Component_3/Content/Topic2.md
  - Component_4:
      - Topic_1: Module_2/Component_4/Content/Topic1.md
      - Topic_2: Module_2/Component_4/Content/Topic2.md